version: "2"
linters:
  default: standard
  enable:
    - misspell
    - goheader
  settings:
    goheader:
      values:
        regexp:
          COPYRIGHT-HOLDER: Copyright © {{ MOD-YEAR-RANGE }} Michael Fero
      template-path: .header
    misspell:
      locale: US
  exclusions:
    paths:
      - _test.go
      - third_party$
      - builtin$
      - examples$
